# =================================================================
# e7-accounting-system 项目的 Wrangler 配置文件 (最终简化版)
# =================================================================

name = "e7-accounting-system"
compatibility_date = "2024-07-16"
pages_build_output_dir = "."

# [核心] 新增的 Cron 触发器配置
[triggers]
# 定义一个 cron 计划，每天在 UTC 时间 2点 运行 [[path]].js 中的 onScheduled 函数
# 您可以根据需要修改此时间
crons = ["*/2 * * * *"]

# =================================================================
# 绑定配置 (仅声明，生产环境的值以Cloudflare仪表盘为准)
# =================================================================

[[kv_namespaces]]
binding = "DB"
id = "8964d53eea3148dc94dcb2c46d3595c3"

[[r2_buckets]]
binding = "DB_BACKUPS"
bucket_name = "e7-accounting-backups"

# =================================================================
# 环境变量 (提醒)
# 您重要的 HEARTBEAT_URL 应该在 Cloudflare 仪表盘中设置为 Secrets。
# =================================================================
